apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-microservico-producao-service
  namespace: tech-challenge-pos-tech
  labels:
    app: tech-challenge-microservico-producao
spec:
  selector:
    app: tech-challenge-microservico-producao
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
