apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-microservico-pagamento-service
  namespace: tech-challenge-pos-tech
  labels:
    app: tech-challenge-microservico-pagamento
spec:
  selector:
    app: tech-challenge-microservico-pagamento
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
