apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-microservico-pedido-service
  namespace: tech-challenge-pos-tech
  labels:
    app: tech-challenge-microservico-pedido
spec:
  selector:
    app: tech-challenge-microservico-pedido
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
